apiVersion: v1
kind: Secret
metadata:
  name: web-api-bff-secret
type: Opaque
stringData:
  APP_KEY: "GkMB04WGWmu9MwY5r8KZi4D2kuRh3w5Y"

  # mongodb
  DB_PASSWORD: "IqJN2QagCrDm"

  # redis
  REDIS_PASSWORD: "3DLWkcctVUhzL4"
